<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Usuario.ABM.Bussiness\Usuario.ABM.Bussiness.csproj" />
    <ProjectReference Include="..\Usuario.ABM.Data\Usuario.ABM.Data.csproj" />
    <ProjectReference Include="..\Usuario.ABM.Entities\Usuario.ABM.Entities.csproj" />
  </ItemGroup>

</Project>
